import { defineBuildConfig } from 'obuild/config'

export default defineBuildConfig({
  entries: [
    {
      type: 'bundle',
      input: [
        './src/index.ts',
        './src/client/index.ts',
        './src/client/adapters/fetch/index.ts',
        './src/client/adapters/ofetch/index.ts',
        './src/client/plugins/index.ts',
        './src/codec/msgpack.ts',
        './src/codec/devalue.ts',
        './src/ws.ts',
        './src/integrations/zod/index.ts',
        './src/integrations/tanstack-query/index.ts',
        './src/integrations/react/index.ts',
        './src/plugins/index.ts',
        './src/plugins/cors.ts',
        './src/plugins/otel.ts',
        './src/plugins/pino.ts',
        './src/plugins/ratelimit.ts',
        './src/adapters/fastify.ts',
        './src/adapters/h3.ts',
        './src/adapters/hono.ts',
        './src/adapters/express.ts',
        './src/adapters/nitro.ts',
        './src/adapters/aws-lambda.ts',
        './src/adapters/elysia.ts',
        './src/adapters/nextjs.ts',
        './src/adapters/sveltekit.ts',
        './src/adapters/remix.ts',
        './src/adapters/astro.ts',
        './src/adapters/solidstart.ts',
        './src/adapters/message-port.ts',
        './src/adapters/nestjs.ts',
        './src/adapters/peer.ts',
        './src/client/openapi.ts',
        './src/contract.ts',
        './src/trpc-interop.ts',
        './src/integrations/ai/index.ts',
        './src/integrations/tanstack-query/ssr.ts',
        './src/client/server.ts',
        './src/plugins/cookies.ts',
        './src/plugins/cache.ts',
      ],
    },
  ],
})
