import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/client/index.ts',
    'src/client/adapters/fetch/index.ts',
    'src/client/adapters/ofetch/index.ts',
    'src/client/plugins/index.ts',
    'src/client/adapters/websocket/index.ts',
    'src/client/consume.ts',
    'src/client/openapi.ts',
    'src/client/server.ts',
    'src/codec/msgpack.ts',
    'src/codec/devalue.ts',
    'src/ws.ts',
    'src/contract.ts',
    'src/trpc-interop.ts',
    'src/integrations/zod/index.ts',
    'src/integrations/tanstack-query/index.ts',
    'src/integrations/tanstack-query/ssr.ts',
    'src/integrations/pinia-colada/index.ts',
    'src/integrations/hey-api/index.ts',
    'src/integrations/react/index.ts',
    'src/integrations/drizzle/index.ts',
    'src/integrations/ai/index.ts',
    'src/integrations/better-auth/index.ts',
    'src/plugins/index.ts',
    'src/plugins/cors.ts',
    'src/plugins/otel.ts',
    'src/plugins/pino.ts',
    'src/plugins/ratelimit.ts',
    'src/plugins/cookies.ts',
    'src/plugins/cache.ts',
    'src/plugins/analytics.ts',
    'src/adapters/express.ts',
    'src/adapters/aws-lambda.ts',

    'src/adapters/nextjs.ts',
    'src/adapters/sveltekit.ts',
    'src/adapters/remix.ts',
    'src/adapters/astro.ts',
    'src/adapters/solidstart.ts',
    'src/adapters/message-port.ts',
    'src/adapters/nestjs.ts',
    'src/adapters/peer.ts',
    'src/broker/index.ts',
    'src/broker/nats.ts',
    'src/broker/redis.ts',
  ],
  format: 'esm',
  outDir: 'dist',
  unbundle: true,
  dts: true,
  clean: true,
  fixedExtension: true,
  skipNodeModulesBundle: true,
})
