/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ChangelogSplatRouteImport } from './routes/changelog/$'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as SponsorsRouteImport } from './routes/sponsors'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogSplatRoute = ChangelogSplatRouteImport.update({
  id: '/changelog/$',
  path: '/changelog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/showcase': typeof ShowcaseRoute
  '/sponsors': typeof SponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/changelog/$': typeof ChangelogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/showcase': typeof ShowcaseRoute
  '/sponsors': typeof SponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/changelog/$': typeof ChangelogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/showcase': typeof ShowcaseRoute
  '/sponsors': typeof SponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/changelog/$': typeof ChangelogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/showcase'
    | '/sponsors'
    | '/api/search'
    | '/blog/$'
    | '/changelog/$'
    | '/docs/$'
    | '/blog/'
    | '/changelog/'
    | '/llms.mdx/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/showcase'
    | '/sponsors'
    | '/api/search'
    | '/blog/$'
    | '/changelog/$'
    | '/docs/$'
    | '/blog'
    | '/changelog'
    | '/llms.mdx/docs/$'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/showcase'
    | '/sponsors'
    | '/api/search'
    | '/blog/$'
    | '/changelog/$'
    | '/docs/$'
    | '/blog/'
    | '/changelog/'
    | '/llms.mdx/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SponsorsRoute: typeof SponsorsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogSplatRoute: typeof BlogSplatRoute
  ChangelogSplatRoute: typeof ChangelogSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$': {
      id: '/changelog/$'
      path: '/changelog/$'
      fullPath: '/changelog/$'
      preLoaderRoute: typeof ChangelogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ShowcaseRoute: ShowcaseRoute,
  SponsorsRoute: SponsorsRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogSplatRoute: BlogSplatRoute,
  ChangelogSplatRoute: ChangelogSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
