/**
 * Code generator — produces Silgi procedures, router, and handler stubs
 * from parsed OpenAPI operations.
 */

import type { SchemaTarget } from './emitters.ts'
import { getEmitter } from './emitters.ts'
import type { ParsedOperation } from './parse.ts'
import { type SchemaContext, createSchemaContext, emitComponentSchemas, jsonSchemaToCode } from './schema-to-code.ts'

// ── Types ──────────────────────────────────────────────

export interface GenerateOptions {
  /** How to group operations: by tag, by first path segment, or flat */
  groupBy?: 'tag' | 'path' | 'flat'
  /** Silgi instance variable name (default: "s") */
  instanceName?: string
  /** Whether to generate handler stubs (default: true) */
  handlers?: boolean
  /** Custom header comment */
  header?: string
  /** Target schema library (default: "zod") */
  schema?: SchemaTarget
}

interface GeneratedFiles {
  /** schemas.gen.ts — validation schemas for all components + operation I/O */
  schemas: string
  /** router.gen.ts — Router definition with procedure builders */
  router: string
  /** handlers/<group>.ts — Handler stub files (if enabled) */
  handlers: Map<string, string>
}

// ── Error code mapping ─────────────────────────────────

const STATUS_TO_ERROR_CODE: Record<number, string> = {
  400: 'BAD_REQUEST',
  401: 'UNAUTHORIZED',
  403: 'FORBIDDEN',
  404: 'NOT_FOUND',
  405: 'METHOD_NOT_ALLOWED',
  408: 'TIMEOUT',
  409: 'CONFLICT',
  410: 'GONE',
  422: 'UNPROCESSABLE_ENTITY',
  429: 'TOO_MANY_REQUESTS',
  500: 'INTERNAL_SERVER_ERROR',
  502: 'BAD_GATEWAY',
  503: 'SERVICE_UNAVAILABLE',
}

// ── Main Generator ─────────────────────────────────────

export function generateCode(
  operations: ParsedOperation[],
  components: Record<string, Record<string, unknown>>,
  options: GenerateOptions = {},
): GeneratedFiles {
  const {
    groupBy = 'tag',
    instanceName = 's',
    handlers: generateHandlers = true,
    header = '// This file is auto-generated by silgi/codegen — DO NOT EDIT',
    schema: target = 'zod',
  } = options

  const emitter = getEmitter(target)
  const ctx = createSchemaContext(target, components)

  // ── 1. Generate operation schemas ──
  const operationSchemas: string[] = []
  const operationSchemaNames = new Map<string, { input?: string; output?: string }>()

  for (const op of operations) {
    const names: { input?: string; output?: string } = {}

    // Input schema: merge path params + query params + body
    const inputSchema = buildInputSchema(op, ctx)
    if (inputSchema) {
      const name = `${op.operationId}Input`
      operationSchemas.push(`export const ${name}Schema = ${inputSchema}`)
      names.input = `${name}Schema`
    }

    // Output schema
    if (op.successSchema) {
      const name = `${op.operationId}Output`
      const code = jsonSchemaToCode(op.successSchema, ctx)
      operationSchemas.push(`export const ${name}Schema = ${code}`)
      names.output = `${name}Schema`
    }

    operationSchemaNames.set(op.operationId, names)
  }

  // Emit component schemas (collected from $ref traversal)
  const componentCode = emitComponentSchemas(ctx)

  const schemasFile = [
    header,
    emitter.importStatement,
    '',
    '// ── Component Schemas ──',
    '',
    componentCode,
    '',
    '// ── Operation Schemas ──',
    '',
    operationSchemas.join('\n\n'),
    '',
  ].join('\n')

  // ── 2. Group operations ──
  const groups = groupOperations(operations, groupBy)

  // ── 3. Generate router ──
  const routerFile = generateRouter(groups, operationSchemaNames, {
    header,
    instanceName,
  })

  // ── 4. Generate handler stubs ──
  const handlerFiles = new Map<string, string>()
  if (generateHandlers) {
    for (const [groupName, ops] of groups) {
      handlerFiles.set(groupName, generateHandlerStub(groupName, ops, operationSchemaNames, header, emitter))
    }
  }

  return { schemas: schemasFile, router: routerFile, handlers: handlerFiles }
}

// ── Input Schema Builder ───────────────────────────────

function buildInputSchema(op: ParsedOperation, ctx: SchemaContext): string | null {
  const e = ctx.emitter
  const parts: { key: string; value: string; required: boolean }[] = []

  // Path params → always required
  for (const p of op.pathParams) {
    parts.push({ key: p.name, value: jsonSchemaToCode(p.schema, ctx), required: true })
  }

  // Query params
  for (const p of op.queryParams) {
    parts.push({ key: p.name, value: jsonSchemaToCode(p.schema, ctx), required: p.required })
  }

  // Body — inline properties if it's an object, otherwise wrap as `body`
  if (op.body) {
    if (op.body.type === 'object' && op.body.properties && !hasOverlap(parts, op.body.properties)) {
      const required = new Set((op.body.required as string[]) ?? [])
      for (const [key, prop] of Object.entries(op.body.properties as Record<string, Record<string, unknown>>)) {
        parts.push({ key, value: jsonSchemaToCode(prop, ctx), required: required.has(key) })
      }
    } else {
      parts.push({ key: 'body', value: jsonSchemaToCode(op.body, ctx), required: op.bodyRequired })
    }
  }

  if (parts.length === 0) return null

  return e.object(parts)
}

function hasOverlap(parts: { key: string }[], properties: Record<string, unknown>): boolean {
  const existing = new Set(parts.map((p) => p.key))
  return Object.keys(properties).some((k) => existing.has(k))
}

// ── Router Generator ───────────────────────────────────

function generateRouter(
  groups: Map<string, ParsedOperation[]>,
  schemaNames: Map<string, { input?: string; output?: string }>,
  opts: { header: string; instanceName: string },
): string {
  const lines: string[] = [
    opts.header,
    "import { silgi } from 'silgi'",
    "import * as schemas from './schemas.gen.ts'",
    '',
    `const ${opts.instanceName} = silgi()`,
    '',
  ]

  // Import handlers
  for (const [groupName] of groups) {
    lines.push(`import * as ${groupName}Handlers from './handlers/${groupName}.ts'`)
  }
  lines.push('')

  // Build router object
  if (groups.size === 1 && groups.has('default')) {
    lines.push('export const router = s.router({')
    for (const op of groups.get('default')!) {
      lines.push(buildProcedureEntry(op, schemaNames, opts, `defaultHandlers.${op.operationId}`, 1))
    }
    lines.push('})')
  } else {
    lines.push(`export const router = ${opts.instanceName}.router({`)
    for (const [groupName, ops] of groups) {
      lines.push(`  ${isSafeIdentifier(groupName) ? groupName : JSON.stringify(groupName)}: {`)
      for (const op of ops) {
        lines.push(buildProcedureEntry(op, schemaNames, opts, `${groupName}Handlers.${op.operationId}`, 2))
      }
      lines.push('  },')
    }
    lines.push('})')
  }

  lines.push('')
  lines.push('export type AppRouter = typeof router')
  lines.push('')

  return lines.join('\n')
}

function buildProcedureEntry(
  op: ParsedOperation,
  schemaNames: Map<string, { input?: string; output?: string }>,
  opts: { instanceName: string },
  handlerRef: string,
  indent: number,
): string {
  const pad = '  '.repeat(indent)
  const s = opts.instanceName
  const names = schemaNames.get(op.operationId) ?? {}

  const chains: string[] = []

  // $route
  const routeParts: string[] = []
  routeParts.push(`path: '${op.silgiPath}'`)
  routeParts.push(`method: '${op.method}'`)
  if (op.summary) routeParts.push(`summary: ${JSON.stringify(op.summary)}`)
  if (op.tags.length) routeParts.push(`tags: [${op.tags.map((t) => JSON.stringify(t)).join(', ')}]`)
  if (op.deprecated) routeParts.push('deprecated: true')
  routeParts.push(`operationId: ${JSON.stringify(op.operationId)}`)
  if (op.successStatus !== 200) routeParts.push(`successStatus: ${op.successStatus}`)
  if (op.security === false) routeParts.push('security: false')
  else if (op.security) routeParts.push(`security: [${op.security.map((s) => JSON.stringify(s)).join(', ')}]`)

  const routeInner = routeParts.map((p) => `${pad}    ${p},`).join('\n')
  chains.push(`.$route({\n${routeInner}\n${pad}  })`)

  if (names.input) chains.push(`.$input(schemas.${names.input})`)
  if (names.output) chains.push(`.$output(schemas.${names.output})`)

  const errorEntries = buildErrorEntries(op, pad)
  if (errorEntries) chains.push(`.$errors(${errorEntries})`)

  chains.push(`.$resolve(${handlerRef})`)

  return `${pad}${op.operationId}: ${s}\n${chains.map((c) => `${pad}  ${c}`).join('\n')},`
}

function buildErrorEntries(op: ParsedOperation, pad: string): string | null {
  if (op.errors.size === 0) return null

  const entries: string[] = []
  for (const [status, { description }] of op.errors) {
    const code = STATUS_TO_ERROR_CODE[status] ?? `ERROR_${status}`
    const finalCode = description && /^[A-Z_]+$/.test(description) ? description : code
    entries.push(`${pad}    ${finalCode}: ${status},`)
  }

  return `{\n${entries.join('\n')}\n${pad}  }`
}

// ── Handler Stub Generator ─────────────────────────────

function generateHandlerStub(
  _groupName: string,
  operations: ParsedOperation[],
  schemaNames: Map<string, { input?: string; output?: string }>,
  header: string,
  emitter: { importStatement: string; inferType: (expr: string) => string },
): string {
  const lines: string[] = [
    header.replace('DO NOT EDIT', 'Fill in the handler implementations'),
    "import { SilgiError } from 'silgi'",
    '',
  ]

  // Check if any operation uses schemas
  const usesSchemas = operations.some((op) => {
    const names = schemaNames.get(op.operationId)
    return names?.input || names?.output
  })
  if (usesSchemas) {
    lines.push(`import type * as schemas from '../schemas.gen.ts'`)
    lines.push('')
  }

  for (const op of operations) {
    const names = schemaNames.get(op.operationId) ?? {}

    const inputType = names.input ? emitter.inferType(`schemas.${names.input}`) : 'undefined'
    const outputType = names.output ? emitter.inferType(`schemas.${names.output}`) : 'unknown'

    if (op.summary) lines.push(`/** ${op.summary} */`)

    lines.push(`export function ${op.operationId}(`)
    lines.push(`  { input, ctx, fail, signal }: {`)
    lines.push(`    input: ${inputType}`)
    lines.push(`    ctx: any`)
    lines.push(`    fail: any`)
    lines.push(`    signal: AbortSignal`)
    lines.push(`  },`)
    lines.push(`): ${outputType} {`)
    lines.push(`  throw new SilgiError({`)
    lines.push(`    code: 'INTERNAL_SERVER_ERROR',`)
    lines.push(`    message: 'Not implemented: ${op.operationId}',`)
    lines.push(`  })`)
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

// ── Grouping ───────────────────────────────────────────

function groupOperations(
  operations: ParsedOperation[],
  groupBy: 'tag' | 'path' | 'flat',
): Map<string, ParsedOperation[]> {
  const groups = new Map<string, ParsedOperation[]>()

  for (const op of operations) {
    let key: string

    switch (groupBy) {
      case 'tag':
        key = op.tags[0] ?? 'default'
        break
      case 'path':
        key = op.path.split('/').filter(Boolean)[0] ?? 'default'
        break
      case 'flat':
        key = 'default'
        break
    }

    key = key.replace(/[^a-zA-Z0-9_]/g, '_')

    if (!groups.has(key)) groups.set(key, [])
    groups.get(key)!.push(op)
  }

  return groups
}

function isSafeIdentifier(s: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(s)
}
