/**
 * Code generator — one file per operation, inline $resolve, URL-based grouping.
 *
 * Output structure:
 *   schemas.gen.ts              — Shared validation schemas
 *   router.gen.ts               — Root router importing all operation files
 *   routes/
 *     pets/
 *       listPets.ts             — Single operation with inline $resolve
 *       createPet.ts
 *     store/
 *       getInventory.ts
 */

import type { SchemaTarget } from './emitters.ts'
import { getEmitter } from './emitters.ts'
import type { ParsedOperation } from './parse.ts'
import type { SchemaContext } from './schema-to-code.ts'
import { createSchemaContext, emitComponentSchemas, jsonSchemaToCode } from './schema-to-code.ts'

// ── Types ──────────────────────────────────────────────

export interface GenerateOptions {
  /** How to group operations into folders: by tag, by first path segment, or flat */
  groupBy?: 'tag' | 'path' | 'flat'
  /** Silgi instance variable name (default: "s") */
  instanceName?: string
  /** Custom header comment */
  header?: string
  /** Target schema library (default: "zod") */
  schema?: SchemaTarget
}

export interface GeneratedFiles {
  /** schemas.gen.ts — validation schemas for all components + operation I/O */
  schemas: string
  /** router.gen.ts — root router importing all operation files */
  router: string
  /** routes/<group>/<operationId>.ts — one file per operation */
  routes: Map<string, string>
}

// ── Error code mapping ─────────────────────────────────

const STATUS_TO_ERROR_CODE: Record<number, string> = {
  400: 'BAD_REQUEST',
  401: 'UNAUTHORIZED',
  403: 'FORBIDDEN',
  404: 'NOT_FOUND',
  405: 'METHOD_NOT_ALLOWED',
  408: 'TIMEOUT',
  409: 'CONFLICT',
  410: 'GONE',
  422: 'UNPROCESSABLE_ENTITY',
  429: 'TOO_MANY_REQUESTS',
  500: 'INTERNAL_SERVER_ERROR',
  502: 'BAD_GATEWAY',
  503: 'SERVICE_UNAVAILABLE',
}

// ── Main Generator ─────────────────────────────────────

export function generateCode(
  operations: ParsedOperation[],
  components: Record<string, Record<string, unknown>>,
  options: GenerateOptions = {},
): GeneratedFiles {
  const {
    groupBy = 'tag',
    instanceName = 's',
    header = '// This file is auto-generated by silgi/codegen — DO NOT EDIT',
    schema: target = 'zod',
  } = options

  const emitter = getEmitter(target)
  const ctx = createSchemaContext(target, components)

  // ── 1. Generate operation schemas ──
  const operationSchemas: string[] = []
  const operationSchemaNames = new Map<string, { input?: string; output?: string }>()

  for (const op of operations) {
    const names: { input?: string; output?: string } = {}

    const inputSchema = buildInputSchema(op, ctx)
    if (inputSchema) {
      const name = `${op.operationId}Input`
      operationSchemas.push(`export const ${name}Schema = ${inputSchema}`)
      names.input = `${name}Schema`
    }

    if (op.successSchema) {
      const name = `${op.operationId}Output`
      const code = jsonSchemaToCode(op.successSchema, ctx)
      operationSchemas.push(`export const ${name}Schema = ${code}`)
      names.output = `${name}Schema`
    }

    operationSchemaNames.set(op.operationId, names)
  }

  const componentCode = emitComponentSchemas(ctx)

  const schemasFile = [
    header,
    emitter.importStatement,
    '',
    '// ── Component Schemas ──',
    '',
    componentCode,
    '',
    '// ── Operation Schemas ──',
    '',
    operationSchemas.join('\n\n'),
    '',
  ].join('\n')

  // ── 2. Group operations into folders ──
  const groups = groupOperations(operations, groupBy)

  // ── 3. Generate one file per operation ──
  const routeFiles = new Map<string, string>()
  for (const [groupName, ops] of groups) {
    for (const op of ops) {
      const filePath = `${groupName}/${op.operationId}`
      routeFiles.set(
        filePath,
        generateOperationFile(op, operationSchemaNames, {
          header: header.replace('DO NOT EDIT', 'Implement your resolver'),
          instanceName,
          schemasImportPath: '../../schemas.gen.ts',
        }),
      )
    }
  }

  // ── 4. Generate root router ──
  const routerFile = generateRootRouter(groups, operationSchemaNames, { header, instanceName })

  return { schemas: schemasFile, router: routerFile, routes: routeFiles }
}

// ── Input Schema Builder ───────────────────────────────

function buildInputSchema(op: ParsedOperation, ctx: SchemaContext): string | null {
  const e = ctx.emitter
  const parts: { key: string; value: string; required: boolean }[] = []

  for (const p of op.pathParams) {
    parts.push({ key: p.name, value: jsonSchemaToCode(p.schema, ctx), required: true })
  }

  for (const p of op.queryParams) {
    parts.push({ key: p.name, value: jsonSchemaToCode(p.schema, ctx), required: p.required })
  }

  if (op.body) {
    if (op.body.type === 'object' && op.body.properties && !hasOverlap(parts, op.body.properties)) {
      const required = new Set((op.body.required as string[]) ?? [])
      for (const [key, prop] of Object.entries(op.body.properties as Record<string, Record<string, unknown>>)) {
        parts.push({ key, value: jsonSchemaToCode(prop, ctx), required: required.has(key) })
      }
    } else {
      parts.push({ key: 'body', value: jsonSchemaToCode(op.body, ctx), required: op.bodyRequired })
    }
  }

  if (parts.length === 0) return null
  return e.object(parts)
}

function hasOverlap(parts: { key: string }[], properties: Record<string, unknown>): boolean {
  const existing = new Set(parts.map((p) => p.key))
  return Object.keys(properties).some((k) => existing.has(k))
}

// ── Single Operation File ──────────────────────────────

function generateOperationFile(
  op: ParsedOperation,
  schemaNames: Map<string, { input?: string; output?: string }>,
  opts: { header: string; instanceName: string; schemasImportPath: string },
): string {
  const s = opts.instanceName
  const names = schemaNames.get(op.operationId) ?? {}
  const lines: string[] = [
    opts.header,
    "import { silgi, SilgiError } from 'silgi'",
    `import * as schemas from '${opts.schemasImportPath}'`,
    '',
    `const ${s} = silgi()`,
    '',
  ]

  if (op.summary) lines.push(`/** ${op.summary} */`)

  // Start the procedure chain
  lines.push(`export const ${op.operationId} = ${s}`)

  // $route
  const routeParts: string[] = []
  routeParts.push(`    path: '${op.silgiPath}',`)
  routeParts.push(`    method: '${op.method}',`)
  if (op.summary) routeParts.push(`    summary: ${JSON.stringify(op.summary)},`)
  if (op.tags.length) routeParts.push(`    tags: [${op.tags.map((t) => JSON.stringify(t)).join(', ')}],`)
  if (op.deprecated) routeParts.push('    deprecated: true,')
  routeParts.push(`    operationId: ${JSON.stringify(op.operationId)},`)
  if (op.successStatus !== 200) routeParts.push(`    successStatus: ${op.successStatus},`)
  if (op.security === false) routeParts.push('    security: false,')
  else if (op.security) routeParts.push(`    security: [${op.security.map((v) => JSON.stringify(v)).join(', ')}],`)

  lines.push(`  .$route({`)
  lines.push(routeParts.join('\n'))
  lines.push(`  })`)

  // $input / $output
  if (names.input) lines.push(`  .$input(schemas.${names.input})`)
  if (names.output) lines.push(`  .$output(schemas.${names.output})`)

  // $errors
  if (op.errors.size > 0) {
    const errorEntries: string[] = []
    for (const [status, { description }] of op.errors) {
      const code = STATUS_TO_ERROR_CODE[status] ?? `ERROR_${status}`
      const finalCode = description && /^[A-Z_]+$/.test(description) ? description : code
      errorEntries.push(`    ${finalCode}: ${status},`)
    }
    lines.push(`  .$errors({`)
    lines.push(errorEntries.join('\n'))
    lines.push(`  })`)
  }

  // $resolve — inline
  lines.push(`  .$resolve(({ input, ctx, fail }) => {`)
  lines.push(`    // TODO: implement ${op.operationId}`)
  lines.push(`    throw new SilgiError({`)
  lines.push(`      code: 'INTERNAL_SERVER_ERROR',`)
  lines.push(`      message: 'Not implemented: ${op.operationId}',`)
  lines.push(`    })`)
  lines.push(`  })`)

  lines.push('')

  return lines.join('\n')
}

// ── Root Router Generator ──────────────────────────────

function generateRootRouter(
  groups: Map<string, ParsedOperation[]>,
  _schemaNames: Map<string, { input?: string; output?: string }>,
  opts: { header: string; instanceName: string },
): string {
  const s = opts.instanceName
  const lines: string[] = [
    opts.header,
    "import { silgi } from 'silgi'",
    '',
  ]

  // Import each operation
  for (const [groupName, ops] of groups) {
    for (const op of ops) {
      lines.push(`import { ${op.operationId} } from './routes/${groupName}/${op.operationId}.ts'`)
    }
  }

  lines.push('')
  lines.push(`const ${s} = silgi()`)
  lines.push('')

  if (groups.size === 1 && groups.has('default')) {
    const ops = groups.get('default')!
    lines.push(`export const router = ${s}.router({`)
    for (const op of ops) {
      lines.push(`  ${op.operationId},`)
    }
    lines.push('})')
  } else {
    lines.push(`export const router = ${s}.router({`)
    for (const [groupName, ops] of groups) {
      const safeName = isSafeIdentifier(groupName) ? groupName : JSON.stringify(groupName)
      lines.push(`  ${safeName}: {`)
      for (const op of ops) {
        lines.push(`    ${op.operationId},`)
      }
      lines.push(`  },`)
    }
    lines.push('})')
  }

  lines.push('')
  lines.push('export type AppRouter = typeof router')
  lines.push('')

  return lines.join('\n')
}

// ── Grouping ───────────────────────────────────────────

function groupOperations(
  operations: ParsedOperation[],
  groupBy: 'tag' | 'path' | 'flat',
): Map<string, ParsedOperation[]> {
  const groups = new Map<string, ParsedOperation[]>()

  for (const op of operations) {
    let key: string

    switch (groupBy) {
      case 'tag':
        key = op.tags[0] ?? 'default'
        break
      case 'path':
        key = op.path.split('/').find(Boolean) ?? 'default'
        break
      case 'flat':
        key = 'default'
        break
    }

    key = key.replace(/[^a-zA-Z0-9_]/g, '_')

    if (!groups.has(key)) groups.set(key, [])
    groups.get(key)!.push(op)
  }

  return groups
}

function isSafeIdentifier(s: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(s)
}
